- name: Create zookeeper group
  become: yes
  ansible.builtin.group:
    name: '{{ zookeeper_group }}'
    state: present
    system: yes
  when: zookeeper_create_user_group | bool
  tags:
    - zookeeper_group

- name: Create zookeeper user
  become: yes
  ansible.builtin.user:
    name: '{{ zookeeper_user }}'
    group: '{{ zookeeper_group }}'
    state: present
    createhome: no
    system: yes
  when: zookeeper_create_user_group | bool
  tags:
    - zookeeper_user