- name: Ensure /etc/dremio directory exists with correct permissions
  become: yes
  ansible.builtin.file:
    path: /etc/dremio
    state: directory

- name: Generate dremio configurations for coordinator
  become: yes
  ansible.builtin.template:
    src: dremio-coordinator.conf.j2
    dest: /etc/dremio/dremio.conf
    mode: 0755

- name: Restart Dremio service
  become: yes
  ansible.builtin.systemd:
    name: dremio.service
    state: restarted